name: CI
on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  testRunnerInEditMode:
    name: Test edit mode ðŸ“
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      - run: echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf
        
      # Activate license
      - name: Run tests
        uses: ./
        with:
          args: -manualLicenseFile UnityLicenseFile.ulf -quit         

      # Configure test runner
      - name: Run tests
        uses: ./
        with:
          args: "-runTests" 
      
      - name: Return License
        if: always()
        uses: ./
        with:
          # Arguments to pass to unity
          args: -returnlicense -quit
