name: CI
on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  testRunnerInEditMode:
    name: Test edit mode ðŸ“
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      - run: echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf

      - name: Activate license
        uses: ./
        continue-on-error: true
        with:
          args: -manualLicenseFile UnityLicenseFile.ulf -quit

      - name: Verify activation
        uses: ./
        with:
          args: -quit

      # Configure test runner
      - name: Run tests
        uses: ./
        with:
          args: -runTests -projectPath .
          workdir: unity-project-with-correct-tests
      
      - name: Return license
        uses: ./
        with:
          args: -returnlicense -quit      

